### ISSUE TITLE
UDP Socket examples

### ISSUE THREAD

**Issue by twood02** [gwAdvNet2015/adv-net-samples#1]
Modify the example code in `socket/` to create a copy that uses UDP sockets instead of TCP. Add commenting explaining the key differences between TCP and UDP.

(name files like `socket/client-udp.c`)

**Comment by hooohu** [comment]
Hello, I claim to solve this issue.

**Comment by hooohu** [comment]
There is an explanation for the difference between TCP and UDP.

The client of TCP use connect() to establish a connection first, then use send() to send a message. The server in TCP use listen() to start waiting for a connection, use accept() to get the connection, and use read to get the message. 

The UDP is working in a different way without the connection. The client of UDP use sendto() to send message directly and the server of UDP use recvfrom() to get that message directly. 

The TCP can secure that the data transmission will be completed. The UDP have a higher speed.

The code has committed in the pull request #25 .

**Comment by twood02** [comment]
Merged. Good job @hantasm.
