### ISSUE TITLE
Advanced Bandwidth Tester

### ISSUE THREAD

**Issue by twood02** [gwAdvNet2015/adv-net-samples#10]
Add features to #9 like:
- Multi threading support with configurable number of threads
- Print output every X seconds
- UDP mode (is this useful?)

Check out the `iperf` program for more ideas!

**Comment by nks5295** [comment]
@twood02: @phil-lopreiato, @atryus and I are claiming this one.

**Comment by twood02** [comment]
ok, that's all you get.  Let the other students have some fun.
