### ISSUE TITLE
timer utility

### ISSUE THREAD

**Issue by twood02** [gwAdvNet2015/adv-net-samples#12]
Write a library to make it easier to measure timing intervals.

This library should let you easily and precisely measure the time of different operations using the CPU cycle counter (rdtsc) or gettimeofday() functions. It should be able to store the information into a histogram (#8).  The library should support 10 different timers which are differentiated using the `timer_id` flag in most functions (this way you can easily start/stop a timer anywhere in your program without having to worry about having a reference to a specific timer struct).  

Usage should be similar to:

```
// make this an enum?
#define TIMER_CYCLES // default mode
#define TIMER_USEC

/* Set the mode to cycle counter or microseconds */
void timer_set_mode(int timer_id, int mode_flag);
/* Return the current mode for a timer */
int timer_get_mode(int timer_id);

/* Start the timer with the specified id.*/
void timer_start(int timer_id);

/* End the specified timer. Returns the number of cycles or microseconds that have elapsed. */
uint64_t timer_end(int timer_id);

/* Return the minimum value measured for the specified timer */
uint64_t timer_min(int timer_id);

/* Return the maximum value measured for the specified timer */
uint64_t timer_max(int timer_id);

/* Return the average value measured for the specified timer */
uint64_t timer_avg(int timer_id);

/* End the specified timer and record the measurement in the histogram */
uint64_t timer_end(int timer_id, struct histogram* hist);
```

Depends on #8.

Note: the cycle counter is specific to each CPU core, so you will get odd results on a multi-core system if your thread moves. Add some documentation to explain this and help avoid it (by pinning pthreads).

**Comment by twood02** [comment]
@SMonaghan @Chryel it looks like you two are the only students who haven't picked an issue yet, and this is the last one left.  You should be able to make a version of this without the histogram library from #8 -- instead, have your program be able to report the average, min, and max for the measurements stored in each counter.

Please post here to confirm that you are working together again and will take on this issue.  Let me know if you have any questions about what it is supposed to do!

**Comment by Chryel** [comment]
Pull request #59. We may have a few questions later on, but nothing at the moment. I also apologize for the late reply, but I thought I had commented previously. Mistake on my part.
