### ISSUE TITLE
Simple Multi-Threaded Server

### ISSUE THREAD

**Issue by twood02** [gwAdvNet2015/adv-net-samples#13]
Make a version of `sockets/server-tcp` which supports multi-threading. Place code in `sockets/multi-threaded/` directory.

The server should start a new thread every time a client connects to it. The new thread should then handle the response. Once the client disconnects, the thread should die.

You may want to have the server do something more interesting for each request, e.g., calculate a Fibonacci sequence, sleep for X milliseconds, run md5 on whatever data is sent to it, respond to an HTTP request, etc. Otherwise it will be hard to tell if there are multiple threads running at once.

Depends on #5.

**Comment by amygara** [comment]
@nks5295 @phil-lopreiato 
Looks like we already did this while doing Issue #5. We'll simplify our example and PR both issues.
