### ISSUE TITLE
HTTP Client

### ISSUE THREAD

**Issue by twood02** [gwAdvNet2015/adv-net-samples#14]
Write a client that performs a single HTTP request and prints the response to the screen.

Leave a comment here with a link to some documentation about the HTTP protocol.

Save code in `sockets/webget.c`.

**Comment by thelimeburner** [comment]
@kstats and @sacul29 would like to work on this issue.

**Comment by thelimeburner** [comment]
Also Joel Klein will work with us. I don't know his github.

**Comment by twood02** [comment]
adding Joel =  @jdk514

**Comment by thelimeburner** [comment]
A great explanation about the HTTP protocol can be found at the following location: http://www.jmarshall.com/easy/http/#structure

Another great explanation for http is the RFC(Request for Comments) which can be found at : http://tools.ietf.org/html/rfc1945

If something is not found in the first example, you will definitely find it in the RFC.
