### ISSUE TITLE
HTTP Server

### ISSUE THREAD

**Issue by twood02** [gwAdvNet2015/adv-net-samples#15]
Write a simple HTTP 1.0 server that can handle GET requests. It should look in the current directory for the files requested and return a proper error code to the user if a file is not found.  Print out debug info about each request made.

Test with:
-  #14 simple http client
- a real browser
- a tool like httperf

**Comment by thelimeburner** [comment]
@kstats and @sacul29 would like to work on this issue.

**Comment by thelimeburner** [comment]
Also Joel Klein will work with us. I don't know his github.

**Comment by twood02** [comment]
adding Joel =  @jdk514

**Comment by thelimeburner** [comment]
A great explanation about the HTTP protocol can be found at the following location: http://www.jmarshall.com/easy/http/#structure 

Another great explanation for http is the RFC(Request for Comments) which can be found at : http://tools.ietf.org/html/rfc1945 

If something is not found in the first example, you will definitely find it in the RFC.
