### ISSUE TITLE
create .gitignore files for sockets/

### ISSUE THREAD

**Issue by twood02** [gwAdvNet2015/adv-net-samples#17]
Create a .gitignore file for the `sockets` directory (and any other relevant ones) that will prevent git from trying to add binaries from the sample code.  Or maybe the makefile should put executables into `build`.

**Comment by wenhuizhang** [comment]
Are theses all  considered as binaries?

# Object files

*.o
*.ko
*.obj
*.elf

# Precompiled Headers

*.gch
*.pch

# Libraries

*.lib
*.a
*.la
*.lo

# Shared objects (inc. Windows DLLs)

_.dll
*.so
*.so._
*.dylib

# Executables

_.exe
*.out
*.app
*.i_86
*.x86_64
*.hex

# Executable files

client-tcp
server-tcp

**Comment by twood02** [comment]
@wenhuizhang - in general, yes those are extensions commonly used for executables and compiled libraries in C. 

For this Issue, the problem was that our Makefile creates executables `server-tcp` and `client-tcp`, which don't have any kind of file extension that the .gitignore file will notice.  That is why @phil-lopreiato needed to specifically add the executable names to the new .gitignore file put into the sockets folder.

Another option would have been to have our compiled executables always go into a build/ folder.  Then you could use a more generic .gitignore file to always ignore them without having to write out each file name.

**Comment by wenhuizhang** [comment]
Got you, sounds like either add 

client-tcp
server-tcp

to gitignore , or modified Makefile with its build directory , and then add

/build

Please correct me if I made it wrong
Thanks, 
Wenhui

**Comment by twood02** [comment]
That is correct--you can see how Phil solved the issue by looking at the pull request he made: https://github.com/gwAdvNet2015/adv-net-samples/pull/18 (then click commits)
