### ISSUE TITLE
In search of team members

### ISSUE THREAD

**Issue by twood02** [gwAdvNet2015/adv-net-samples#21]
If you are looking for a team to work with, post here so you can find others!

**Comment by hooohu** [comment]
Hello, My name is Chenghu He. I missed the first class so I don't have any group now. If you're still finding a team member, please let me know. Thanks.

**Comment by twood02** [comment]
Another option for those of you who are looking for someone to work with is to post a comment to claim an issue, but leave a note saying you are happy to have someone else help you out with it.

(or just do things on your own for now -- the easy issues should all be pretty easy)
