### ISSUE TITLE
IP Loopup Example

### ISSUE THREAD

**Issue by twood02** [gwAdvNet2015/adv-net-samples#3]
Write a program in `sockets/iplookup.c` that takes a hostname on the command line and returns the primary IP of the server.  The `getaddrinfo()` function in the socket library should be able to do the lookup for you.

**Comment by wenhuizhang** [comment]
INADDR_LOOPBACK   ? @huyang

**Comment by twood02** [comment]
I'm not sure what this comment is asking? Are you two going to work on this issue?  If so I will assign it to you.

**Comment by wenhuizhang** [comment]
Yep，I am asking if HuYang wants to collaborate on this issue, yet I am
still waiting for his reply.

Thanks,

Wenhui

On Wed, Jan 14, 2015 at 10:49 AM, Tim Wood notifications@github.com wrote:

> I'm not sure what this comment is asking? Are you two going to work on
> this issue? If so I will assign it to you.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gwAdvNet2015/adv-net-samples/issues/3#issuecomment-69936470
> .

## 

V/R,

Wenhui Zhang

Email: wenhui@gwmail.gwu.edu
           Telephone: 1-(703) 424 3193

**Comment by wenhuizhang** [comment]
We decided to work on #2 and #4 thanks, @huyang1988 @pradeep-k @wenhuizhang

**Comment by Chryel** [comment]
@smonaghan and I have decided to work on this.

Pull request as of now is #34.
