### ISSUE TITLE
Fix all makefiles

### ISSUE THREAD

**Issue by twood02** [gwAdvNet2015/adv-net-samples#43]
Most of our makefiles are incomplete or have bugs in them.  Go forth and fix them.

**Comment by phil-lopreiato** [comment]
We should also define a standard for the Makefiles. It would be good for each file to have an `all` target that is default (so it'll build everything in the directory), and also a `clean` target that deleted anything compiled by the file.

**Comment by twood02** [comment]
yes, I agree.  Whoever does this should follow this suggestion.

**Comment by thelimeburner** [comment]
Team Katie, Lucas and Joel will take this as our bug to fix.
