### ISSUE TITLE
libpcap packet sniffer

### ISSUE THREAD

**Issue by twood02** [gwAdvNet2015/adv-net-samples#46]
[Libpcap](http://www.tcpdump.org/) is the library used by programs like tcpdump to intercept network traffic.  Let's build our own simple packet sniffer that can intercept packets being sent or received by your computer!

Your program should use libpcap to listen in on packets sent out a device provided as a command line argument.  It should then print out some kind of basic header information for each packet that it intercepts.  The tcpdump site has some examples of how to do this--you can use that code as a base, but clean it up and better document it.  Note that most of the documentation listed there is over ten years old, so the library may have changed.

Put your code in a new `sniffer` directory.  Start with the simplest possible example which can print out info for a packet in `sniffer/simple_sniff.c`.

**Comment by thelimeburner** [comment]
Team Katie,Joel, Lucas will claim this one.
