### ISSUE TITLE
Counter Data Structure Comparison

### ISSUE THREAD

**Issue by twood02** [gwAdvNet2015/adv-net-samples#47]
Lossy Counters and HyperLogLog Counters are two extremely efficient probabilistic data structure for counting how often certain "keys" appear in a data stream.  This is commonly used for network services, for example to count how often how often different web URLs appear.

For this Issue you should find a C implementation of each of these data structures and compare their efficiency.  Measure the time to insert a key into the counter and to read entries from the counter.

Check this blog post to learn about hyperloglog and for a link to the Redis implementation.  If you copy any of the redis code into this repo, be sure to check the Redis license to be sure that is allowed (and copy whatever copyright/license files are necessary).

Place all code into `datastructs/counters`.

**Comment by twood02** [comment]
@hantasm this is a good option for you since you are already looking at this code.

**Comment by hooohu** [comment]
Hi, I will work on this issue with @zhangwei1984 . Thanks.
