### ISSUE TITLE
Pthreads examples

### ISSUE THREAD

**Issue by twood02** [gwAdvNet2015/adv-net-samples#5]
Create an example program that shows how to create multiple threads. Put the code in the `threads/` directory.

**Comment by nks5295** [comment]
@nks5295, @phil-lopreiato, @atryus

**Comment by nks5295** [comment]
@twood02 @phil-lopreiato @atryus When solving this issue, we basically did #13 so we're dropping this one and doing that one instead.

**Comment by twood02** [comment]
OK, I will unassign you from this issue.  **If someone else wants to take this on add a comment.**

**Comment by pradeep-k** [comment]
I will be doing this as I couldn't contribute anything for issue: ring buffer data structure.

**Comment by twood02** [comment]
I can't assign the issue to you until you accept the organization request--you can probably do that here: https://github.com/gwAdvNet2015

**Comment by pradeep-k** [comment]
I accepted the invite. Thanks.
