### ISSUE TITLE
DPDK Examples

### ISSUE THREAD

**Issue by twood02** [gwAdvNet2015/adv-net-samples#50]
Write some simple DPDK applications that show how it works.  Put the programs in a new `dpdk/` directory.  Do not include the entire DPDK library source.  Make these programs:
- [ ] `sender.c`: takes command line arguments for src/dest: IP, port, and MAC, and a message length. It then sends a single UDP packet to the designated address.  The body of the packet can be any data of the specified length.
- [ ] `mirror.c`: receives packets and then immediately sends them out again
- [ ] `multimirror.c` same as above, but uses multiple threads
- [ ] `switch.c`: Has two threads that each receive packets on a different NIC port.  Packets received in port 1 are sent out port 2 and vice versa.

All programs should have an optional `-v` verbose flag which cause them to print out information about each packet received.

Each program should be as simple and clearly documented as possible.

**Comment by zhangwei1984** [comment]
Work with @hantasm
