### ISSUE TITLE
Ping Pong Latency Timer

### ISSUE THREAD

**Issue by twood02** [gwAdvNet2015/adv-net-samples#6]
Create a program in `socket/latency/` that measures the round trip delay between a client and a server.

The program should have a flag that indicates whether it should act as a server (waits for a new connection) or a client (requires a server name/ip argument). Once connected, the client sends a counter starting at 1. The server immediately replies with the same value.  The client measures the time difference between when the counter was sent and the response was received. These "ping pong" messages are repeated a configurable number of times (default 100) and then the min, average, and maximum delay are reported.

Ideally this should use #12 Timer Utility Library, but to start you can just use gettimeofday or something similar.

**Comment by twood02** [comment]
Note: I think there is a socket option flag that controls whether messages are sent immediately or if it waits for a buffer to be filled or for a flush.  This will affect the RTT!

**Comment by hooohu** [comment]
Hello, I would like to work on this issue.

**Comment by hooohu** [comment]
Hello, the pull request for this is #28
