### ISSUE TITLE
SDN Port Translator

### ISSUE THREAD

**Issue by twood02** [gwAdvNet2015/adv-net-samples#64]
Write a pox program that will rewrite all TCP packet destined for port X (specified on the command line) to be destined for TCP port Y.  All traffic should be broadcast or managed by a learning switch.

**Comment by wenhuizhang** [comment]
@huyang1988  @pradeep-k  @wenhuizhang

**Comment by pradeep-k** [comment]
Plz assign this to me.  Talked to wenhui on this.
@huyang1988 @wenhuizhang

**Comment by pradeep-k** [comment]
I am still working on this.

**Comment by pradeep-k** [comment]
It seems that BBN-PortForwarding.py does the trick. 
I tested it. 
Howver, there was just a small hack that I used, import statement in this file was like this:
                    from SimpleL2Learning import SimpleL2LearningSwitch
And, when I modified this line to this:
                    from BBN-SimpleL2Learning import SimpleL2LearningSwitch
It had issues with underscore. So, to test it I simply copied BBN-SimpleL2Learning.py and made a new copy as SimpleL2Learning.py

I think, after figuring out underscore issue, I can raise a pull request. I will be searching for this underscore issue.
Let me know if I need to do something else.

**Comment by twood02** [comment]
was your problem with underscores (_) or dashes (-)?

Phil had a problem with the BBN filenames with dashes not importing correctly, so he changed them to undescores in pull request #89.  I'm not sure if you are using an older version of the repo and getting the same problem he had, or if you've pulled the latest but are getting a new problem because of his change.

**Comment by pradeep-k** [comment]
My bad. The problem was with dashes(-). 
I checked the latest repo, the name has been changed. So, I don't have to do any changes. We can close this issue.

Just to make this comment complete, I needed to change the port_forward.config to put the ip of my geni VMs. Howver, it will be deployment specific, so need to submit the changes.
