### ISSUE TITLE
SDN Mirror

### ISSUE THREAD

**Issue by twood02** [gwAdvNet2015/adv-net-samples#65]
Write a pox program that acts as a learning switch, but also mirrors all traffic from a specified IP address (first command line argument) to another ethernet port (second command line argument).  Use tcpdump or the packetsniffer to verify that the second host gets the traffic (but that other hosts do not).

**Comment by phil-lopreiato** [comment]
@nks5295 @atryus and yours truly can do this one

**Comment by twood02** [comment]
no immediate due date for this, but you may find it useful practice for your geni competition entry.
