### ISSUE TITLE
SDN Learning Switch

### ISSUE THREAD

**Issue by twood02** [gwAdvNet2015/adv-net-samples#66]
Write a simple pox program that initially broadcasts all traffic, but learns which MACs are associated with each port as it receives packets.

Don't just copy one of the existing solutions.

**Comment by hooohu** [comment]
Hello, I and @zhangwei1984 would like to work on it.

**Comment by hooohu** [comment]
I applied this issue but now I'm not working on SDN. 

So, there would be no update in this week.

**Comment by twood02** [comment]
I think the BBN examples solve this issue, so we don't need to do it.
