### ISSUE TITLE
Ping Pong UDP

### ISSUE THREAD

**Issue by twood02** [gwAdvNet2015/adv-net-samples#7]
This is an improvement for #6 once it is completed.
- Add a command line flag that specifies whether to use TCP or UDP sockets.
- Count how many packets are dropped and include that information in the output.

**Comment by akorzan** [comment]
I would like to claim this one as #6 has been completed.

**Comment by twood02** [comment]
I've sent you an invitation to the organization.  Once you join I can assign this to you.

**Comment by twood02** [comment]
@akorzan  you can work on this part later to catch up, and should focus on hw 1 in your personal repo for now.

**Comment by twood02** [comment]
solved by #37
