### ISSUE TITLE
bug: simple web server and client 

### ISSUE THREAD

**Issue by twood02** [gwAdvNet2015/adv-net-samples#74]
**http-server**

Sometimes it works and sometimes it segfaults.  From looking at the code, I personally think it should always segfault ;) Hint: it has to do with your http_response struct.

```
$ ./server-http
listening on port: 1234
Method: GET, Request: /, Version: HTTP/1.0

File does not exist
response object created
Method: GET, Request: /hello.html, Version: HTTP/1.0

response object created
Segmentation fault: 11
```

---

**webget.c**
Trying to specify a specific file to download does not work:

```
$ ./web-get -h localhost -p 1234 -m "/hello.html"
GET / HTTP/1.0


HTTP/1.1 404
Host: host.name
Content-Type: HTML
Content-Length: 125

<html><head></head><body><h1 style='max-width:600px;margin:auto;margin-top:25px'>ERROR 404: File Not Found</h1></body></html>
Done.
```

Also, "-m" is a confusing flag letter.  I think -f (for file) would be better.

**Comment by kstats** [comment]
Since this was our bug, me, @sacul29 and @jdk514 will take this one too!
